sudo: require
language: generic 
services:
    - docker

before_install:
    - docker build -t devashar/docker-react -f Dockerfile.dev .
    
script:
    script:
        - docker run -e CI=true devashar/docker-react:latest npm run test -- --coverage