language: generic
sudo: required

services:
  - docker  

before_install:
  - docker build -t devashar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devashar/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    reigon: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucker_name: "elasticbeanstalk-us-east-2-384483145854"
    bucker_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
